export default [
  {name: 'ADD/ADHD - Childhood', href: 'https://www.webmd.com/add-adhd/childhood-adhd/default.htm'},
  {name: 'ADHD - Childhood', href: 'https://www.webmd.com/add-adhd/default.htm'},
  {name: 'Allergies', href: 'https://www.webmd.com/allergies/default.htm'},
  {name: "Alzheimer's", href: 'https://www.webmd.com/alzheimers/default.htm'},
  {name: 'Ankylosing Spondylitis', href: 'https://www.webmd.com/ankylosing-spondylitis/default.htm'},
  {name: 'Anxiety Disorders', href: 'https://www.webmd.com/anxiety-panic/default.htm'},
  {name: 'ADD/ADHD - Childhood', href: 'https://www.webmd.com/add-adhd/childhood-adhd/default.htm'},
  {name: 'Arthritis', href: 'https://www.webmd.com/arthritis/default.htm'},
  {name: 'Asthma', href: 'https://www.webmd.com/asthma/default.htm'},
  {name: 'Back Pain', href: 'https://www.webmd.com/back-pain/default.htm'},
  {name: 'Cancer', href: 'https://www.webmd.com/cancer/default.htm'},
  {name: "Children's Vaccines", href: 'https://www.webmd.com/children/vaccines/default.htm'},
  {name: 'Cholesterol', href: 'https://www.webmd.com/cholesterol-management/default.htm'},
  {name: 'Cold, Flu, & Cough', href: 'https://www.webmd.com/cold-and-flu/default.htm'},
  {name: 'COPD', href: 'https://www.webmd.com/lung/copd/default.htm'},
  {name: 'Coronavirus', href: 'https://www.webmd.com/coronavirus'},
  {name: 'ADD/ADHD - Childhood', href: 'https://www.webmd.com/add-adhd/childhood-adhd/default.htm'},
  {name: 'Depression', href: 'https://www.webmd.com/depression/default.htm'},
  {name: 'Diabetes', href: 'https://www.webmd.com/diabetes/type-2-diabetes'},
  {name: 'Digestive Disorders', href: 'https://www.webmd.com/digestive-disorders/default.htm'},
  {name: 'Eye Health', href: 'https://www.webmd.com/eye-health/default.htm'},
  {name: 'Health & Balance', href: 'https://www.webmd.com/balance/default.htm'},
  {name: 'Heart Health', href: 'https://www.webmd.com/heart/default.htm'},
  {name: 'Heartburn/GERD', href: 'https://www.webmd.com/heartburn-gerd/default.htm'},
  {name: 'Hypertension', href: 'https://www.webmd.com/hypertension-high-blood-pressure/default.htm'},
  {name: 'Lung Cancer', href: 'https://www.webmd.com/lung-cancer/default.htm'},
  {name: 'Mental Health', href: 'https://www.webmd.com/mental-health/default.htm'},
  {name: 'Migraines', href: 'https://www.webmd.com/migraines-headaches/default.htm'},
  {name: 'Multiple Myeloma', href: 'https://www.webmd.com/cancer/multiple-myeloma/default.htm'},
  {name: 'Multiple Sclerosis', href: 'https://www.webmd.com/multiple-sclerosis/default.htm'},
  {name: 'Oral Care', href: 'https://www.webmd.com/oral-health/default.htm'},
  {name: 'Orthopedics', href: 'https://www.webmd.com/orthopedics/default.htm'},
  {name: 'Osteoporosis', href: 'https://www.webmd.com/osteoporosis/default.htm'},
  {name: 'Ovarian Cancer', href: 'https://www.webmd.com/ovarian-cancer/default.htm'},
  {name: 'Prostate Cancer', href: 'https://www.webmd.com/prostate-cancer/default.htm'},
  {name: 'Psoriasis', href: 'https://www.webmd.com/skin-problems-and-treatments/psoriasis/default.htm'},
  {name: 'Rheumatoid Arthritis', href: 'https://www.webmd.com/rheumatoid-arthritis/default.htm'},
  {name: 'Schizophrenia', href: 'https://www.webmd.com/schizophrenia/default.htm'},
  {name: 'Sexual Conditions', href: 'https://www.webmd.com/sexual-conditions/default.htm'},
  {name: 'Skin Problems', href: 'https://www.webmd.com/skin-problems-and-treatments/default.htm'},
  {name: 'Sleep Disorders', href: 'https://www.webmd.com/sleep-disorders/default.htm'},
];